
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS manager;
DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS restaurant;
DROP TABLE IF EXISTS order_;
DROP TABLE IF EXISTS comment;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phone_number TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  region TEXT NOT NULL,
  address TEXT NOT NULL,
  credit FLOAT NOT NULL
);

CREATE TABLE manager (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL
--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  author_id INTEGER NOT NULL,
--  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE restaurant (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  region TEXT NOT NULL,
  address TEXT NOT NULL
);